import { Trip } from './types';

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'goa-trip',
    name: 'Goa Trip',
    emoji: '🌴',
    members: [
      { id: 'member-priya', name: 'Priya', avatarColor: '#f472b6' },
      { id: 'member-aarav', name: 'Aarav', avatarColor: '#ddb8ff' },
      { id: 'member-kabir', name: 'Kabir', avatarColor: '#f9bd22' },
      { id: 'member-rohan', name: 'Rohan', avatarColor: '#62259b' },
      { id: 'member-kavya', name: 'Kavya', avatarColor: '#ca9700' },
    ],
    expenses: [
      {
        id: 'exp-1',
        title: 'Dinner at Thalassa',
        amount: 4200,
        paidBy: 'member-priya',
        paymentMode: 'UPI',
        splitBetween: ['member-priya', 'member-aarav', 'member-kabir', 'member-rohan'],
        date: 'Yesterday',
        icon: '🍽️',
      },
      {
        id: 'exp-2',
        title: 'Scooter Rental',
        amount: 1500,
        paidBy: 'member-kabir',
        paymentMode: 'CASH',
        splitBetween: ['member-kabir', 'member-aarav'],
        date: '2 days ago',
        icon: '🛵',
      },
      {
        id: 'exp-3',
        title: 'Drinks & Snacks',
        amount: 3850,
        paidBy: 'member-rohan',
        paymentMode: 'UPI',
        splitBetween: [
          'member-priya',
          'member-aarav',
          'member-kabir',
          'member-rohan',
          'member-kavya',
        ],
        date: '3 days ago',
        icon: '🍻',
      },
      {
        id: 'exp-4',
        title: 'Beachside Villa Advance',
        amount: 15300,
        paidBy: 'member-priya',
        paymentMode: 'UPI',
        splitBetween: [
          'member-priya',
          'member-aarav',
          'member-kabir',
          'member-rohan',
          'member-kavya',
        ],
        date: '4 days ago',
        icon: '🏖️',
      },
    ],
    settlements: [],
  },
  {
    id: 'weekend-cabin',
    name: 'Weekend Cabin',
    emoji: '🏕️',
    members: [
      { id: 'member-priya', name: 'Priya', avatarColor: '#f472b6' },
      { id: 'member-aarav', name: 'Aarav', avatarColor: '#ddb8ff' },
      { id: 'member-rohan', name: 'Rohan', avatarColor: '#62259b' },
    ],
    expenses: [
      {
        id: 'exp-c-1',
        title: 'Cabin Booking at Lonavala',
        amount: 12000,
        paidBy: 'member-aarav',
        paymentMode: 'UPI',
        splitBetween: ['member-priya', 'member-aarav', 'member-rohan'],
        date: 'Last week',
        icon: '🏡',
      },
      {
        id: 'exp-c-2',
        title: 'BBQ & Groceries',
        amount: 3600,
        paidBy: 'member-priya',
        paymentMode: 'CASH',
        splitBetween: ['member-priya', 'member-aarav', 'member-rohan'],
        date: 'Last week',
        icon: '🥩',
      },
    ],
    settlements: [],
  },
];
